name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ChinoKafuu
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      ALLOW_CHANNEL_ID_GEMINI: ${{ secrets.ALLOW_CHANNEL_ID_GEMINI }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - name: Replace config placeholders with secrets
      run: |
        sed -i "s/Your_Discord_Token/${DISCORD_TOKEN}/g" Configs/config.json
        sed -i 's/"allowChannelID_gemini": "Your_Channel_ID (Integer only)"/"allowChannelID_gemini": "'${ALLOW_CHANNEL_ID_GEMINI}'"/g' Configs/config.json
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run for a short time
      run: |
        timeout 20s dotnet run --no-build --configuration Release
